name: Deploy new version
on:
  pull_request:
    branches: ["dev"]
  push:
    branches: ["dev"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: mof1us/frontend_mti_dev

jobs:
  build-application-and-tests:
    runs-on: ubuntu-latest
    environment:
      NEXT_PUBLIC_IS_ON_DEV=true
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 # или нужная вам
          run_install: false

      - name: Setup Node.js and cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

  build-docker-image-and-push:
    runs-on: ubuntu-latest
    needs: build-application-and-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker HUB
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: mof1us/frontend_mti_dev:latest
          load: true
          push: true
          build-args: |
            NEXT_PUBLIC_IS_ON_DEV=true

  restart-service:
    needs: build-docker-image-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SHH and restart service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            sudo systemctl restart mti_dev_startup
            

  deploy-error:
    if: ${{ always() && (needs.build-application.result == 'failure' || needs.build-and-push-docker-image.result == 'failure' || needs.restart-service.result == 'failure') }}
    needs: [ build-application-and-tests, build-docker-image-and-push, restart-service ]
    runs-on: ubuntu-latest
    steps:
      - name: Send error notification
        uses: appleboy/telegram-action@v0.1.2
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Ошибка при деплое tournaments-mti-service-dev в ветку dev на GitHub Actions. Проверьте логи выполнения."